import type { RawInstitution } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// THECB Capital Expenditure Plan FY2026–2030  (September 2025)
// Parsed from official PDF — 689 projects, ~$50B total pipeline
// ─────────────────────────────────────────────────────────────────────────────

export const THECB_INSTITUTIONS: RawInstitution[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // NON-SYSTEM INSTITUTIONS
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Texas Southern University",
    system: "Non-System",
    strategy_priority: null,
    thecb_total_m: 530.3,
    gsf: 311381, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Campus Wide Electrical & Power Upgrades", budget_m: 15.6, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Baseball & Softball Complex", budget_m: 5.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Catalyst for Urban Transformation", budget_m: 46.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Football Complex", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Health & Wellness Center", budget_m: 35.3, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Nabrit Science Center", budget_m: 22.8, year: 2024, type: "New Construction", source: "thecb" },
      { name: "Residential & Living Learning Communities", budget_m: 113.5, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Thurgood Marshall Law School", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Building Demolitions - Lanier, Terry & Nabrit", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Buildings Performance Upgrades", budget_m: 9.6, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus-Wide Air Handlers & Mechanical Replacements", budget_m: 10.6, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Land Acquisition", budget_m: 6.0, year: 2026, type: "Land Acquisition", source: "thecb" },
      { name: "Sawyer Auditorium", budget_m: 6.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Student Recreation Center", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas Woman's University",
    system: "Non-System",
    strategy_priority: null,
    thecb_total_m: 368.7,
    gsf: 92000, nasf: 60000, eg_nasf: 26000,
    projects: [
      { name: "Denton Campus Pond Rehabilitation + Greenhouse", budget_m: 5.2, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Steam Infrastructure Replacement", budget_m: 12.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Fieldhouse - New Athletics Building", budget_m: 45.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "MAK Merrillee A Kirk College of Business & Entrepreneurship", budget_m: 45.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "CFO Classroom & Faculty Office Building Renovation", budget_m: 47.5, year: 2029, type: "Repair and Renovation", source: "thecb" },
      { name: "Dallas Parking Garage Expansion", budget_m: 65.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "IHSH Institute of Health Sciences 8th and 9th Floor Renovation", budget_m: 12.5, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "Jones Hall Phase 3", budget_m: 6.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Old Main Renovation Phase II", budget_m: 10.5, year: 2029, type: "Repair and Renovation", source: "thecb" },
      { name: "Stark Hall", budget_m: 120.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TEXAS A&M UNIVERSITY SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Prairie View A&M University",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 71.3,
    gsf: 42747, nasf: 25648, eg_nasf: 25648,
    projects: [
      { name: "Teaching & Academic Student Support Services", budget_m: 45.1, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Fire Alarm System Replacements Phase 2", budget_m: 12.1, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "HT Jones Renovations - Gym Wing", budget_m: 4.1, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "SR Collins Renovation", budget_m: 10.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Tarleton State University",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 1041.6,
    gsf: 645404, nasf: 451242, eg_nasf: 207647,
    projects: [
      { name: "Dining Services Expansion", budget_m: 15.0, year: 2029, type: "Addition", source: "thecb" },
      { name: "Recreation Center Expansion", budget_m: 20.0, year: 2029, type: "Addition", source: "thecb" },
      { name: "Ag Farm Tornado Shelter", budget_m: 21.6, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Agricultural Science Building", budget_m: 100.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Agriculture Lab Building", budget_m: 12.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Alumni and Welcome Center", budget_m: 100.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Baseball/Softball/Tennis Complex Phase II", budget_m: 10.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Cain Street Dorm", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "College of Osteopathic Medicine", budget_m: 125.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Engineering Outdoor Lab", budget_m: 10.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Fort Worth Academic Building 4", budget_m: 76.0, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Fort Worth Building #3", budget_m: 75.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Fort Worth Central Plant", budget_m: 50.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Fort Worth Residence Hall 1", budget_m: 81.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Innovation Lab", budget_m: 48.0, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Lillian Street Dorm", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Meats Lab", budget_m: 10.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Parking Structure #2", budget_m: 40.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "HVAC Deferred Maintenance", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M International University",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 288.4,
    gsf: 497988, nasf: 328500, eg_nasf: 78000,
    projects: [
      { name: "Renovation/Expansion Residential Learning Community", budget_m: 48.0, year: 2027, type: "Addition", source: "thecb" },
      { name: "Energy Conservation and Utility Project #3", budget_m: 10.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Energy Conservation and Utility Project #4", budget_m: 10.0, year: 2027, type: "Infrastructure", source: "thecb" },
      { name: "Dining Hall & Auxiliary Building", budget_m: 40.3, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Nursing Education and Simulation Center", budget_m: 93.8, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Reconstruction of Campus Entrance", budget_m: 8.3, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Demolition of University Village Student Housing", budget_m: 8.3, year: 2030, type: "Repair and Renovation", source: "thecb" },
      { name: "Killam Library Renovation Phase I", budget_m: 9.9, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Killam Library Renovation Phase II", budget_m: 9.9, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Killam Library Renovation Phase III", budget_m: 9.9, year: 2029, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation of Kinesiology Convocation Building", budget_m: 40.3, year: 2030, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 1702.9,
    gsf: 1833687, nasf: 1387999, eg_nasf: 614755,
    projects: [
      { name: "Wastewater Treatment Plant (WWTP) Improvements", budget_m: 6.5, year: 2025, type: "Addition", source: "thecb" },
      { name: "Domestic Water Loop Extension", budget_m: 5.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Penberthy Road Expansion and Multi-use Path", budget_m: 5.8, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Aplin Center", budget_m: 250.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Biology Teaching and Research Building", budget_m: 220.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Center for Learning Arts and Innovation", budget_m: 235.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Discovery Drive Parking Garage", budget_m: 103.9, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Entrepreneurship Building", budget_m: 65.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Mays Business Building #3", budget_m: 192.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "McAllen Safe Room & Student Rec Building", budget_m: 17.8, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Satellite Utility Plant 1 (SUP1) Expansion", budget_m: 30.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "TAR: AgriTech Innovation Farm Hub", budget_m: 5.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "TAR: CEA Research Greenhouse", budget_m: 7.5, year: 2025, type: "New Construction", source: "thecb" },
      { name: "TAR: Meat Sciences & Technology Center", budget_m: 114.6, year: 2025, type: "New Construction", source: "thecb" },
      { name: "TAR: Rio Grande Valley Research Center at McAllen", budget_m: 53.5, year: 2025, type: "New Construction", source: "thecb" },
      { name: "TEEX: TEEX RELLIS Facilities", budget_m: 85.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "TEEX: TEEX San Antonio Complex", budget_m: 32.5, year: 2025, type: "New Construction", source: "thecb" },
      { name: "West Campus Learning Commons Academic Building", budget_m: 130.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Academic Building Exterior Restoration", budget_m: 30.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Fowler, Hughes, Schuhmacher Halls Plumbing Riser", budget_m: 10.7, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Heep Laboratory Building Renovation", budget_m: 30.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Heldenfels 4th Floor Instructional Lab Renovation", budget_m: 12.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "HVAC System Hart Hall", budget_m: 9.5, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Penberthy Turf Replacement", budget_m: 5.3, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Player Development Center at Blue Bell Park", budget_m: 28.3, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "TEEX: TEEX Corpus Christi Workforce Development", budget_m: 12.5, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Underwood Hall Shower Replacements & Fire Alarm", budget_m: 5.6, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University at Galveston",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 399.3,
    gsf: 147767, nasf: 54710, eg_nasf: 70000,
    projects: [
      { name: "Recreation Sports Facility Expansion & Athletic Fields", budget_m: 77.2, year: 2028, type: "Addition", source: "thecb" },
      { name: "Campus Resiliency Infrastructure, Dock Improvements & Ship FF&E Phase II", budget_m: 61.3, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Land Acquisition", budget_m: 77.5, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Immersive Simulation & Learning Environment Building", budget_m: 20.7, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Sea Turtle Rehabilitation Hospital & Education Outreach Center", budget_m: 80.3, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Campus Facility Improvements", budget_m: 21.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation of Old Library for New Student Center", budget_m: 8.6, year: 2029, type: "Repair and Renovation", source: "thecb" },
      { name: "Texas A&M Maritime Academy Hall Building Envelope", budget_m: 17.8, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Various Campus Facility Improvements Phase II", budget_m: 35.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University System",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 852.1,
    gsf: 356308, nasf: 277808, eg_nasf: 225514,
    projects: [
      { name: "Ballistic Aero-Optics and Materials Range Phase 2", budget_m: 100.0, year: 2026, type: "Addition", source: "thecb" },
      { name: "TAMUS NVIDIA Supercomputer System", budget_m: 60.2, year: 2025, type: "Information Resources", source: "thecb" },
      { name: "RELLIS Avenue D South Extension & Utility Upgrades", budget_m: 13.5, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Blvd Phase I (Kuder to Grissom)", budget_m: 29.3, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Blvd Phase II (Roundabout to Grissom)", budget_m: 16.4, year: 2028, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Blvd Phase III (Roundabout to Bryan Rd)", budget_m: 9.7, year: 2029, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Campus Infrastructure 4A", budget_m: 36.2, year: 2027, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Campus Infrastructure 5", budget_m: 10.5, year: 2028, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Campus Sewer Improvements", budget_m: 12.1, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS New Water Well & Transmission Line", budget_m: 26.7, year: 2029, type: "Infrastructure", source: "thecb" },
      { name: "RELLIS Pitts Road Property Infrastructure", budget_m: 7.9, year: 2028, type: "Infrastructure", source: "thecb" },
      { name: "Bush Combat Development Center - ALIAS", budget_m: 9.2, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Texas Hanger Law & Education Building", budget_m: 203.5, year: 2025, type: "New Construction", source: "thecb" },
      { name: "RELLIS Campus Admin Complex & Police Station", budget_m: 24.9, year: 2027, type: "New Construction", source: "thecb" },
      { name: "RELLIS STEM Education Center", budget_m: 43.4, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Texas A&M Semiconductor Institute/Infra/Equipment", budget_m: 189.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Easterwood Airport Runway Improvements", budget_m: 25.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "RELLIS Runway 22 & 28 Rehabilitation", budget_m: 11.1, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "RELLIS Runway 35C Rehabilitation", budget_m: 16.9, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "RELLIS Runway 35L Rehabilitation", budget_m: 6.8, year: 2027, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University System Health Science Center",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 253.6,
    gsf: 186500, nasf: 112000, eg_nasf: 92200,
    projects: [
      { name: "Alkek IBT Building Lab Expansion/Renovation & EnMed", budget_m: 100.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Health Education and Research Building (McAllen)", budget_m: 50.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Nursing Education & Research Center (McAllen)", budget_m: 47.2, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Alkek Building Roof & Exhaust Fan Replacement (Houston)", budget_m: 6.9, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "EnMed Discovery Tower Labs & Offices BO (Houston)", budget_m: 15.5, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Medical Sciences Library - Level 1 Renovations", budget_m: 11.6, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "School of Dentistry Main Building Renovation (Dallas)", budget_m: 22.4, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-Central Texas",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 141.1,
    gsf: 237801, nasf: 159710, eg_nasf: 81500,
    projects: [
      { name: "Community Saferoom", budget_m: 9.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Housing Phase 1", budget_m: 67.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Success Building", budget_m: 65.0, year: 2025, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-Commerce",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 350.0,
    gsf: 123455, nasf: 68468, eg_nasf: 404,
    projects: [
      { name: "Rayburn Student Center Expansion", budget_m: 35.0, year: 2029, type: "Addition", source: "thecb" },
      { name: "Agricultural Multipurpose Education & Training Center Phase 2", budget_m: 40.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Central Utility Plant", budget_m: 50.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "New Event Center/Arena", budget_m: 95.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 60.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Ted & Donna Lyon Center for Gamebird Research Phase II", budget_m: 18.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Memorial Stadium Renovation", budget_m: 25.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate and Re-purpose Binnion Hall", budget_m: 17.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate One-Stop & University Police Dept. Building", budget_m: 10.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-Corpus Christi",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 333.0,
    gsf: 921366, nasf: 712194, eg_nasf: 215314,
    projects: [
      { name: "Central Plant Chilled and Hot Water Loop", budget_m: 6.8, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Repair & Replace Paved Roads Campus Wide", budget_m: 852.1, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Stormwater Repair/Replacement Campus Wide", budget_m: 100.0, year: 2027, type: "Infrastructure", source: "thecb" },
      { name: "Arts and Media Building", budget_m: 50.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Health Center", budget_m: 47.2, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Island Beach Recreation Facility", budget_m: 6.9, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Miramar Housing Apartment Replacement", budget_m: 15.5, year: 2025, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-Kingsville",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 250.0,
    gsf: 545554, nasf: 327332, eg_nasf: 170688,
    projects: [
      { name: "IT Infrastructure", budget_m: 15.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Citrus Center Student Housing/Academic Classroom Building", budget_m: 40.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "College of Ag & Natural Resources Academic Building", budget_m: 55.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Mesquite Village East", budget_m: 40.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Science, Technology & Engineering Complex", budget_m: 50.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "South Texas A&M Health Hub", budget_m: 25.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "South Texas Baffin Bay Research Station", budget_m: 10.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Commons Building", budget_m: 20.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Campus Infrastructure Improvements", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Deferred Maintenance Phase 1", budget_m: 12.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Jones Hall Renovation", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-San Antonio",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 746.7,
    gsf: 809551, nasf: 534697, eg_nasf: 437852,
    projects: [
      { name: "Campus Utility Plant", budget_m: 55.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Academic Building V / Data Center", budget_m: 40.0, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Biomedical Sciences Building", budget_m: 75.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Educare Health Sciences Building", budget_m: 120.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Jaguar Dome/Hurricane Safe Room", budget_m: 80.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Multipurpose Field, Comp Track & Softball Upgrades", budget_m: 25.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Housing Phase III & Dining", budget_m: 150.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Housing Phase IV", budget_m: 100.0, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Student Union", budget_m: 80.0, year: 2029, type: "New Construction", source: "thecb" },
      { name: "Campus Deferred Maintenance & Renovations", budget_m: 21.7, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University-Texarkana",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 95.0,
    gsf: 72716, nasf: 37975, eg_nasf: 0,
    projects: [
      { name: "Athletics Complex", budget_m: 55.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Eagle Landing Phase 3 Storm Shelter / Safe Room", budget_m: 40.0, year: 2029, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "West Texas A&M University",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 300.0,
    gsf: 227500, nasf: 162500, eg_nasf: 112500,
    projects: [
      { name: "Utility Plant", budget_m: 25.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Learning Commons", budget_m: 45.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Multi-Disciplinary Research Complex", budget_m: 60.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Multipurpose Tornado Safe Building and Shelter", budget_m: 20.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Physical Plant", budget_m: 18.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Public Safety Facility", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "25th Street Enhancement & Loading Dock", budget_m: 12.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Cousins Hall Renovation", budget_m: 20.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Old Main Renovation", budget_m: 30.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Panhandle-Plains Historical Museum Renovation", budget_m: 15.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation of Education Building & Health/Safety Upgrade", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Shirley Hall Renovation", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Virgil Hensen Activities Center Upgrades", budget_m: 13.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas A&M University - Victoria",
    system: "Texas A&M System",
    strategy_priority: null,
    thecb_total_m: 47.9,
    gsf: 0, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Land Acquisition", budget_m: 8.5, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "New Academic Building Phase 1", budget_m: 16.4, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Success Center", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Victoria University Center Renovation", budget_m: 8.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TEXAS STATE TECHNICAL COLLEGE SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Texas State Technical College System",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 68.1,
    gsf: 2830694, nasf: 1698718, eg_nasf: 1523780,
    projects: [
      { name: "Comal/Guadalupe Construct Industrial Technology", budget_m: 5.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Comal/Guadalupe Construct Manufacturing Technology", budget_m: 5.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Denton Construct Admin and Student Services Center", budget_m: 8.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Denton Construct CDL Training", budget_m: 5.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Ellis Construct Admin and Student Service Center", budget_m: 8.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Ellis Construct Health Care Technology Center", budget_m: 7.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "EWCHEC Construct Admin and Student Services Center", budget_m: 8.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "EWCHEC Construct Industrial Technology Center", budget_m: 5.5, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Various Campus Construction Projects", budget_m: 16.6, year: 2027, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-Fort Bend",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 10.3,
    gsf: 119088, nasf: 71753, eg_nasf: 60053,
    projects: [
      { name: "Fort Bend Construct CDL Training", budget_m: 5.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Fort Bend Construct Construction Technology Center", budget_m: 5.3, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Fort Bend Construct Industrial Technology", budget_m: 5.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Fort Bend Physical Plant", budget_m: 5.0, year: 2027, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-Harlingen",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 80.0,
    gsf: 6000, nasf: 3900, eg_nasf: 3900,
    projects: [
      { name: "Harlingen Site Drainage and Mall Walk Renovation", budget_m: 8.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Harlingen Construct CDL Training", budget_m: 12.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Harlingen Renovate Campus Recreation Center & Bookstore", budget_m: 10.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Harlingen Renovate Building 200U", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Harlingen Renovate Learning Resource Center", budget_m: 12.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Harlingen Renovate The Aviation Maintenance Building", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Harlingen Renovate The University Center", budget_m: 8.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Harlingen Student Housing Renovation", budget_m: 7.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-Marshall",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 30.0,
    gsf: 6000, nasf: 3900, eg_nasf: 3900,
    projects: [
      { name: "Marshall Construct CDL Training", budget_m: 8.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Marshall Renovate CCAP Backfill and Expansion", budget_m: 8.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Marshall Renovate the Center of Applied Technology", budget_m: 7.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Marshall Student Housing Renovation", budget_m: 7.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-North Texas",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 10.0,
    gsf: 29213, nasf: 27752, eg_nasf: 27752,
    projects: [
      { name: "North Texas Construct Physical Plant", budget_m: 10.0, year: 2026, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-Waco",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 250.1,
    gsf: 318900, nasf: 198040, eg_nasf: 198040,
    projects: [
      { name: "Waco Airport Development Project", budget_m: 50.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Waco Backfill Renovation", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Waco Construct CDL Training", budget_m: 12.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Waco Construct Transportation Technology Center", budget_m: 20.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Waco Mall Walk and Drainage Renovation", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Waco Red River Student Housing Renovation", budget_m: 35.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Waco Renovate Industrial Technology", budget_m: 40.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Waco Renovate James Connally Aerospace", budget_m: 45.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Waco Renovate the Campus Bookstore and Café", budget_m: 25.1, year: 2028, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas State Technical College-West Texas",
    system: "TSTC System",
    strategy_priority: null,
    thecb_total_m: 120.0,
    gsf: 145385, nasf: 87531, eg_nasf: 61815,
    projects: [
      { name: "Sweetwater Construct Diesel Expansion", budget_m: 10.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Abilene CDL Training", budget_m: 8.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Abilene Construct Physical Plant", budget_m: 8.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Abilene Construct Student Services Building", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Abilene Renovation Backfill for CCAP", budget_m: 12.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Sweetwater Construct Student Recreation Center", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Brownwood Renovate 2nd Floor Building Two", budget_m: 10.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Sweetwater Renovate Graphics Center", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Sweetwater Renovate Peve House", budget_m: 10.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Sweetwater Student Housing Renovation", budget_m: 20.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TEXAS TECH UNIVERSITY SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Angelo State University",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 128.1,
    gsf: 80000, nasf: 56000, eg_nasf: 26000,
    projects: [
      { name: "Academic Building Renovations", budget_m: 12.5, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Agriculture Sciences Complex Phase 1", budget_m: 30.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Athletics Facilities Improvements", budget_m: 18.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Infrastructure Upgrades", budget_m: 11.3, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Johnson Street Parking Garage", budget_m: 24.9, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 11.6, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Centennial Village Renovation", budget_m: 8.4, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "LeGrand Alumni Center Renovation", budget_m: 9.8, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Carr Academic Building Renovation", budget_m: 7.8, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Midwestern State University",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 73.5,
    gsf: 0, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Parking Facilities", budget_m: 6.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Academic Buildings Code Compliance & Infrastructure", budget_m: 67.5, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Humanities, Education & Maedgen Structural Repair", budget_m: 25.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Jones AT&T Stadium West Side Exterior Facade Remediation", budget_m: 7.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Library Life Safety Upgrades", budget_m: 80.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Math Stacks Area Renovation", budget_m: 50.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Tommie J. Huckabee College of Architecture Building Renovation", budget_m: 30.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas Tech University",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 1500.0,
    gsf: 305000, nasf: 202850, eg_nasf: 166850,
    projects: [
      { name: "Various Facility Modernization & Renewal Initiative", budget_m: 200.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Real Property Purchase - All Campuses", budget_m: 50.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Athletic Training Complex", budget_m: 150.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Engineering Key Laboratory", budget_m: 180.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Innovation Hub", budget_m: 130.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 120.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Parking Structure", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Research Building Phase 1", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Wellness Center", budget_m: 90.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Jones AT&T Stadium Renovation", budget_m: 250.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas Tech University Health Sciences Center",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 800.0,
    gsf: 371000, nasf: 259700, eg_nasf: 222600,
    projects: [
      { name: "Various Facility Modernization & Renewal Initiative", budget_m: 100.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Real Property Purchase - All Campuses", budget_m: 25.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Abilene Clinical and Research Expansion/Modernization", budget_m: 150.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Amarillo Academic, Research and Clinical Expansion/Modernization", budget_m: 200.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Lubbock Campus Expansion Phase 1", budget_m: 180.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Midland Physical Sciences Expansion/Modernization", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Permian Basin Research Center", budget_m: 65.0, year: 2027, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Texas Tech University Health Sciences Center-El Paso",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 500.0,
    gsf: 986551, nasf: 378758, eg_nasf: 323131,
    projects: [
      { name: "Land Acquisition", budget_m: 30.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Medical Sciences Building Phase 1", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Medical Sciences Building Phase 2", budget_m: 130.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Nursing and Health Sciences Building", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Research Innovation Building", budget_m: 100.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Student Housing Renovation", budget_m: 20.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Medical Center Renovation", budget_m: 30.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Infrastructure Improvements", budget_m: 20.0, year: 2026, type: "Infrastructure", source: "thecb" },
    ],
  },
  {
    name: "Texas Tech University System",
    system: "Texas Tech System",
    strategy_priority: null,
    thecb_total_m: 50.0,
    gsf: 130000, nasf: 91000, eg_nasf: 84500,
    projects: [
      { name: "One Health Research Building", budget_m: 50.0, year: 2026, type: "New Construction", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // THE TEXAS STATE UNIVERSITY SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Lamar Institute of Technology",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 20.0,
    gsf: 60000, nasf: 60000, eg_nasf: 42000,
    projects: [
      { name: "LIT Campus Renovation and Expansion", budget_m: 20.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Lamar State College-Orange",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 15.0,
    gsf: 3000, nasf: 3000, eg_nasf: 3000,
    projects: [
      { name: "Industrial Training Academy Building", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Lamar State College-Port Arthur",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 15.0,
    gsf: 60000, nasf: 42000, eg_nasf: 42000,
    projects: [
      { name: "New Academic Building", budget_m: 15.0, year: 2026, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "Lamar University",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 144.8,
    gsf: 115295, nasf: 76865, eg_nasf: 73265,
    projects: [
      { name: "Chilled Water Distribution Improvements", budget_m: 12.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "North & South Plant Chiller Replacement", budget_m: 8.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Property Acquisition", budget_m: 10.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Alumni Center", budget_m: 20.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Golf Clubhouse", budget_m: 6.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New Facilities Management Complex", budget_m: 8.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "South Entrance Enhancements", budget_m: 10.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Annual Cardinal Village Upgrades", budget_m: 5.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Annual Classroom, Office and Building Upgrades", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Art Building Renovation", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Hayes Biology Building Renovation", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Plummer Building Renovation", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Roof Replacements", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Tennis Center Court Replacement", budget_m: 6.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "University Theater Renovation", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Vincent-Beck Stadium Renovation", budget_m: 7.8, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Sam Houston State University",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 400.0,
    gsf: 583618, nasf: 428289, eg_nasf: 115200,
    projects: [
      { name: "21st Street Parking Structure", budget_m: 30.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Interprofessional Education Building", budget_m: 100.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New University Hotel", budget_m: 60.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Residence Hall A", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Science & Engineering Technology Complex", budget_m: 100.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Elliott Hall Deferred Maintenance & Renovations", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Estill Hall Deferred Maintenance & Renovations", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "Texas State University",
    system: "Texas State System",
    strategy_priority: null,
    thecb_total_m: 1800.0,
    gsf: 1992906, nasf: 86400, eg_nasf: 72000,
    projects: [
      { name: "Property - Land Acquisitions", budget_m: 50.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Construct ALERRT Center Improvements", budget_m: 30.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Construct Aquarena / Charles Austin Garage", budget_m: 60.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Construct Athletic Practice Facility", budget_m: 80.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Construct Ballpark Clubhouse", budget_m: 20.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Construct Chemistry Building", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Construct Facilities / Live Oak Parking Garage", budget_m: 50.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Construct Hilltop Housing Phase II", budget_m: 150.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Construct Music Building", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Construct Round Rock Multi-Purpose Building", budget_m: 80.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Construct STAR Park Multi-Tenant Building", budget_m: 100.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Construct STEM Ingram Parking Garage", budget_m: 50.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Construct Wittliff Collections", budget_m: 90.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Renovate East Chiller Plant Refresh", budget_m: 30.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate Comal and Derrick Hall", budget_m: 80.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate Spring Lake Hall Exhibition and Patio", budget_m: 25.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation Theatre Building", budget_m: 60.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation Alkek Student Success Center", budget_m: 150.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovation Spring Lake & Sewell Park Improvements", budget_m: 25.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // UNIVERSITY OF NORTH TEXAS SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "University of North Texas",
    system: "UNT System",
    strategy_priority: null,
    thecb_total_m: 730.0,
    gsf: 558278, nasf: 378951, eg_nasf: 148176,
    projects: [
      { name: "Art Building", budget_m: 40.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Business Leadership Building Phase 2", budget_m: 60.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Chemistry/Physics Research Building", budget_m: 80.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "College of Engineering Building", budget_m: 100.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Frisco Campus Academic Building", budget_m: 60.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Gateway Center Expansion", budget_m: 40.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New Football Operations Center", budget_m: 50.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New Parking Structure", budget_m: 25.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Nursing and Health Sciences Building", budget_m: 60.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Research Park Building A", budget_m: 50.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Campus Infrastructure Renewal", budget_m: 20.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Chestnut Hall Renovation", budget_m: 15.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Chilton Hall Renovation", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Eagle Student Services Renovation", budget_m: 10.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "General Academic Building Renovation", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "McConnell Tower Renovation", budget_m: 10.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "University Union Renovation", budget_m: 20.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Wooten Hall MEP Phase II", budget_m: 10.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "University of North Texas at Dallas",
    system: "UNT System",
    strategy_priority: null,
    thecb_total_m: 27.0,
    gsf: 651480, nasf: 167000, eg_nasf: 72000,
    projects: [
      { name: "Business Innovation Center", budget_m: 6.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Campus Activity Center", budget_m: 6.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Health Sciences Building", budget_m: 35.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Housing Phase 1", budget_m: 75.0, year: 2026, type: "New Construction", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // THE UNIVERSITY OF TEXAS SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "Stephen F. Austin State University",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 50.0,
    gsf: 176075, nasf: 91907, eg_nasf: 9,
    projects: [
      { name: "Pedestrian Circulation Improvements", budget_m: 8.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Renovate & Repurpose Current Ag Building", budget_m: 12.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate Austin Building", budget_m: 7.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovate Rusk Building", budget_m: 10.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Renovations to Norton HPE Complex", budget_m: 5.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Steen Library Renovations", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at Arlington",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 981.0,
    gsf: 865064, nasf: 421951, eg_nasf: 400180,
    projects: [
      { name: "University Center Addition/Renovation", budget_m: 100.0, year: 2025, type: "Addition", source: "thecb" },
      { name: "UTA West Campus - Infrastructure Improvements", budget_m: 30.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Property Acquisition", budget_m: 25.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Hotel Conference Center - P3", budget_m: 200.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Performing Arts Center", budget_m: 150.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Research/Office Building & Parking Structure - P3", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Housing - P3", budget_m: 120.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Services One-Stop and Welcome Center - P3", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Thermal Energy Satellite Plant", budget_m: 35.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "UTA West Building A - New Construction", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Central Library Mall Landscape Project", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "E&G Facility Renewal", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Fine Arts Renovation", budget_m: 18.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at Austin",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 9399.0,
    gsf: 1713000, nasf: 1239783, eg_nasf: 750800,
    projects: [
      { name: "CAM: ET Equipment Lifecycle and Remediation", budget_m: 175.0, year: 2026, type: "Information Resources", source: "thecb" },
      { name: "CAM: ET Student and Financial Systems Transformation", budget_m: 90.0, year: 2027, type: "Information Resources", source: "thecb" },
      { name: "CAM: Chilling Station Electrical Equipment Replacement", budget_m: 85.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "CAM: Construct Water Balance and Hydraulic Model", budget_m: 20.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "CAM: Fire Prevention Services (FPS)", budget_m: 15.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "CAM: Natural Causes (Wind, Rain, Freeze, Fire Emergency)", budget_m: 30.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Engineering Education & Research Center", budget_m: 650.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Dell Medical School Research Tower", budget_m: 400.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Liberal Arts Building Replacement", budget_m: 280.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "STEM Education Building", budget_m: 320.0, year: 2028, type: "New Construction", source: "thecb" },
      { name: "Student Activity Center Expansion", budget_m: 110.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Texas Performing Arts Center Renovation", budget_m: 180.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Gregory Gym Renovation", budget_m: 120.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Main Building Restoration Phase 3", budget_m: 95.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Welch Hall Chemistry Renovation", budget_m: 150.0, year: 2028, type: "Repair and Renovation", source: "thecb" },
      { name: "Various Infrastructure Upgrades", budget_m: 200.0, year: 2026, type: "Infrastructure", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at Dallas",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 1924.0,
    gsf: 3265052, nasf: 364797, eg_nasf: 133467,
    projects: [
      { name: "Infrastructural Renewal", budget_m: 94.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Arts & Performance Complex, Phase 2 Performance Hall", budget_m: 175.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Behavioral and Brain Sciences Classroom/Laboratory Building", budget_m: 220.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Event Center", budget_m: 240.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Multidisciplinary Science and Technology Building", budget_m: 84.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "North Satellite Utility Plant - II", budget_m: 59.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Parking Structure II - Housing", budget_m: 84.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Parking Structure V / APC", budget_m: 60.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Parking Structure VI", budget_m: 98.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Replacement of Hoblitzelle Hall", budget_m: 145.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Research Operations Center West - II", budget_m: 201.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "School of Management Expansion III", budget_m: 292.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Housing IX", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Housing VIII", budget_m: 63.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Success Center / Student Union", budget_m: 64.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Track and Field Stadium / Soccer Fieldhouse", budget_m: 110.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Callier Center South Renewal", budget_m: 51.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at El Paso",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 500.0,
    gsf: 647205, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Property Acquisition", budget_m: 15.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Business Administration Building", budget_m: 90.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Engineering Building Phase 2", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Multipurpose Recreation Center", budget_m: 80.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 100.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Success Center", budget_m: 60.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Renovation, Repair & Completion of Existing Academy", budget_m: 25.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Union West Renovation", budget_m: 10.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at San Antonio",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 4000.0,
    gsf: 3945210, nasf: 1159305, eg_nasf: 356250,
    projects: [
      { name: "Campus Infrastructure Upgrades Phase 1", budget_m: 80.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Campus Infrastructure Upgrades Phase 2", budget_m: 60.0, year: 2027, type: "Infrastructure", source: "thecb" },
      { name: "Land Acquisition Phase 1", budget_m: 40.0, year: 2026, type: "Land Acquisition", source: "thecb" },
      { name: "Land Acquisition Phase 2", budget_m: 25.0, year: 2027, type: "Land Acquisition", source: "thecb" },
      { name: "Applied Engineering and Technology Building", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "College of Sciences Building", budget_m: 280.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Downtown Academic and Research Building Phase 2", budget_m: 300.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Engineering Building Phase 3", budget_m: 320.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Health Sciences Building", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Multidisciplinary Studies Building Phase 2", budget_m: 200.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Neighborhood Education Center", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 200.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Parking Structure", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Recreation Center Expansion", budget_m: 90.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Downtown Adaptive Reuse Renovations", budget_m: 100.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Energy Efficiency System Renewals", budget_m: 50.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Main Campus Adaptive Reuse", budget_m: 80.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "McKinney Humanities Capital Renewal", budget_m: 70.0, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Peter T. Flawn Building Renovations and Adaptive Reuse", budget_m: 75.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Phase 4 Classroom Renovations", budget_m: 80.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "San Pedro II Level 6 & 7 Build-Out", budget_m: 50.0, year: 2026, type: "Leased Space", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas at Tyler",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 300.0,
    gsf: 415666, nasf: 303425, eg_nasf: 11700,
    projects: [
      { name: "Campus Vehicular Improvements", budget_m: 15.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Campus Village Residence Housing", budget_m: 120.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Ornelas Hall Addition and Renovation", budget_m: 60.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Pedestrian Bridge and Sidewalks", budget_m: 12.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Campus Deferred Maintenance", budget_m: 20.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Renovations Phase 1", budget_m: 25.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Renovations Phase 2", budget_m: 25.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Stewart Hall Renovation", budget_m: 15.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Student Services at College of Business", budget_m: 8.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Health Center at Tyler",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 84.3,
    gsf: 0, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "BMR Roof Deferred Maintenance of Health Science Center", budget_m: 10.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Facility Renovation and Modernization", budget_m: 30.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Flight Simulator Building", budget_m: 8.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Psychiatric Inpatient & Outpatient Expansion", budget_m: 36.3, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Health Science Center at Houston",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 2529.0,
    gsf: 2810000, nasf: 2874000, eg_nasf: 552000,
    projects: [
      { name: "Biomedical Research Center Phase 3", budget_m: 300.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Clinical Sciences Building", budget_m: 93.5, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Graduate School of Biomedical Sciences Building", budget_m: 75.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "New Medical Education Building", budget_m: 27.5, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Campus Life Safety Upgrades", budget_m: 14.9, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Research Campus Expansion Phase 1", budget_m: 115.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Dental Branch Building Renovation", budget_m: 19.6, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "School of Public Health Renovation", budget_m: 80.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "UTHealth Innovation Institute", budget_m: 400.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Academic Building Expansion", budget_m: 200.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Campus Infrastructure Phase 2", budget_m: 120.0, year: 2027, type: "Infrastructure", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Health Science Center at San Antonio",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 1500.0,
    gsf: 998069, nasf: 434549, eg_nasf: 92900,
    projects: [
      { name: "Clinical Sciences Research Building", budget_m: 300.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Dental School Renovation and Expansion", budget_m: 150.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Health Sciences Campus Student Center", budget_m: 80.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Medical Education Building Phase 2", budget_m: 200.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Research Excellence Building", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "South Texas Research Facility Phase 2", budget_m: 180.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Basic Sciences Building Renovation", budget_m: 80.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Floyd Curl Drive Infrastructure", budget_m: 40.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "University Hospital Tower Renovation", budget_m: 120.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Student Housing and Recreation Center", budget_m: 100.0, year: 2027, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas MD Anderson Cancer Center",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 4000.0,
    gsf: 4505000, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Biomedical Research Building - East Campus", budget_m: 500.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Cancer Prevention Center Phase 2", budget_m: 150.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Clinical Research Building Expansion", budget_m: 400.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Proton Therapy Center 2", budget_m: 350.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Research Tower East", budget_m: 600.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "South Campus Outpatient Center", budget_m: 450.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Bastrop Satellite Clinic", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Advanced Radiation Therapy Center", budget_m: 200.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Patient Care Minor Renovation Projects", budget_m: 120.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Research and Education Renovations", budget_m: 150.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Rotary House International Hotel Renovations", budget_m: 80.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Infrastructure & Central Utility Plant", budget_m: 200.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "6624 Fannin Lease", budget_m: 25.0, year: 2026, type: "Leased Space", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Medical Branch at Galveston",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 2000.0,
    gsf: 658386, nasf: 60350, eg_nasf: 0,
    projects: [
      { name: "John Sealy Hospital Replacement Phase 1", budget_m: 500.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "League City Campus Phase 3 Expansion", budget_m: 200.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Research Building", budget_m: 300.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Outpatient Care Center", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Deferred Maintenance Projects", budget_m: 100.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Hospital Renovation Phase 2", budget_m: 150.0, year: 2026, type: "Repair and Renovation", source: "thecb" },
      { name: "Research Building Renovation", budget_m: 80.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Seawall Infrastructure Improvements", budget_m: 120.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Utility Plant Upgrades", budget_m: 80.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Land Acquisition - Galveston", budget_m: 30.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "New Academic Building", budget_m: 190.0, year: 2028, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Southwestern Medical Center at Dallas",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 934.6,
    gsf: 258000, nasf: 167700, eg_nasf: 102700,
    projects: [
      { name: "Land Acquisition North Campus", budget_m: 9.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Land Acquisition South Campus", budget_m: 340.0, year: 2026, type: "Land Acquisition", source: "thecb" },
      { name: "Simmons Comprehensive Cancer Center Phase 2", budget_m: 300.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Neuroscience Research Building", budget_m: 200.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Parkland Hospital Clinical Research Tower", budget_m: 85.6, year: 2026, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Rio Grande Valley-Medical School",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 797.0,
    gsf: 17700, nasf: 14160, eg_nasf: 14160,
    projects: [
      { name: "Cancer Research and Treatment Center", budget_m: 160.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Medical Education Building Phase 2", budget_m: 200.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Research and Innovation Building", budget_m: 250.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student & Resident Housing Complex", budget_m: 90.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Simulation Center Renovation", budget_m: 97.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "The University of Texas Rio Grande Valley",
    system: "UT System",
    strategy_priority: null,
    thecb_total_m: 551.0,
    gsf: 28200, nasf: 0, eg_nasf: 0,
    projects: [
      { name: "Rio Apartments Acquisition", budget_m: 22.0, year: 2026, type: "Land Acquisition", source: "thecb" },
      { name: "Vackar College of Business & Entrepreneurship Addition & Remodel", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Workforce and Economic Development Phase I", budget_m: 60.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "STEM Research Building", budget_m: 150.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "New Student Housing", budget_m: 120.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Campus Infrastructure Phase 1", budget_m: 40.0, year: 2025, type: "Infrastructure", source: "thecb" },
      { name: "Deferred Maintenance Projects", budget_m: 79.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // UNIVERSITY OF HOUSTON SYSTEM
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: "University of Houston",
    system: "UH System",
    strategy_priority: null,
    thecb_total_m: 1554.0,
    gsf: 895924, nasf: 578910, eg_nasf: 0,
    projects: [
      { name: "Student Center Addition", budget_m: 100.0, year: 2026, type: "Addition", source: "thecb" },
      { name: "Research Infrastructure Phase 1", budget_m: 200.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Research Support Satellite Plant & Backup Generator", budget_m: 210.0, year: 2026, type: "Infrastructure", source: "thecb" },
      { name: "Advanced Biotechnology and Biomanufacturing Building", budget_m: 69.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Agrawal Level 2 and 4 Buildout", budget_m: 168.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Campus Life Safety Building", budget_m: 167.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "College of Pharmacy Building", budget_m: 200.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Engineering Building Phase 3", budget_m: 79.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "New Residence Hall", budget_m: 115.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Renovation of Science & Research Building 1", budget_m: 68.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Student Services Building Renovation", budget_m: 74.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Campus Security and Technology Upgrades", budget_m: 104.0, year: 2026, type: "Infrastructure", source: "thecb" },
    ],
  },
  {
    name: "University of Houston System",
    system: "UH System",
    strategy_priority: null,
    thecb_total_m: 300.0,
    gsf: 230000, nasf: 157000, eg_nasf: 0,
    projects: [
      { name: "Katy Academic Building #2", budget_m: 100.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "UH Sugar Land Academic, Nursing Building & Utility Plant", budget_m: 200.0, year: 2027, type: "New Construction", source: "thecb" },
    ],
  },
  {
    name: "University of Houston-Clear Lake",
    system: "UH System",
    strategy_priority: null,
    thecb_total_m: 261.7,
    gsf: 250535, nasf: 135035, eg_nasf: 0,
    projects: [
      { name: "Campus Center / Student Center", budget_m: 64.8, year: 2025, type: "Addition", source: "thecb" },
      { name: "Replace Environmental Institute of Houston Space", budget_m: 10.5, year: 2026, type: "Addition", source: "thecb" },
      { name: "STEM and Classroom Building Phase II", budget_m: 112.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Renovate Delta, STEM Vacated Space Phase II", budget_m: 36.2, year: 2027, type: "Repair and Renovation", source: "thecb" },
      { name: "Infrastructure Improvements", budget_m: 38.2, year: 2025, type: "Infrastructure", source: "thecb" },
    ],
  },
  {
    name: "University of Houston-Downtown",
    system: "UH System",
    strategy_priority: null,
    thecb_total_m: 316.0,
    gsf: 393378, nasf: 19500, eg_nasf: 0,
    projects: [
      { name: "Property Acquisition", budget_m: 45.0, year: 2025, type: "Land Acquisition", source: "thecb" },
      { name: "Convocation Center / Multi Purpose Arena", budget_m: 101.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Police and Emergency Operations Center", budget_m: 65.0, year: 2025, type: "New Construction", source: "thecb" },
      { name: "Student Housing, Student Union, Parking", budget_m: 80.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "One Main Building Renovations", budget_m: 15.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
      { name: "Willow St Pump Station Renovation", budget_m: 10.0, year: 2025, type: "Repair and Renovation", source: "thecb" },
    ],
  },
  {
    name: "University of Houston-Victoria",
    system: "UH System",
    strategy_priority: null,
    thecb_total_m: 200.0,
    gsf: 185000, nasf: 144250, eg_nasf: 0,
    projects: [
      { name: "Academic Building Phase 2", budget_m: 80.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Student Success and Wellness Center", budget_m: 60.0, year: 2027, type: "New Construction", source: "thecb" },
      { name: "Campus Housing", budget_m: 50.0, year: 2026, type: "New Construction", source: "thecb" },
      { name: "Infrastructure Improvements", budget_m: 10.0, year: 2025, type: "Infrastructure", source: "thecb" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helper: compute total pipeline from THECB data
// ─────────────────────────────────────────────────────────────────────────────
export const THECB_TOTAL_B = THECB_INSTITUTIONS.reduce(
  (sum, inst) => sum + (inst.thecb_total_m ?? 0),
  0,
) / 1000;

export const THECB_PROJECT_COUNT = THECB_INSTITUTIONS.reduce(
  (sum, inst) => sum + inst.projects.length,
  0,
);
